<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $user = [
            [
                'name' => 'Administrator',
                'username' => 'admin',
                'password' => Hash::make('hashclaw137'),
                'role' => 'admin',
                'phone' => '0',
                'email' => 'IT@pintex.co.id',
                'entitas_all' => '1',
                'entitas_pintex' => '1',
                'entitas_tfi' => '1',
                'p_master' => '1',
                'p_pengadaan' => '1',
                'c_permintaan' => '1',
                'c_persetujuan' => '1',
                'c_email' => '1',
                'c_pembelian' => '1',
                'c_status' => '1',
                'p_gudang' => '1',
                'c_stock' => '1',
                'c_penerimaan' => '1',
                'c_pengiriman' => '1',
                'c_sample' => '1',
                'c_transit' => '1',
                'c_mutasi' => '1',
                'p_teknik' => '1',
                'c_servis' => '1',
                'c_retur' => '1',
                'c_pengambilan' => '1',
                'p_laporan' => '1',
                'c_lap_pemakaian' => '1',
                'c_lap_pembelian' => '1',
                'c_lap_stock' => '1',
                'p_pengaturan' => '1',
                'c_pengguna' => '1',
            ],

            [
                'name' => 'Administrator',
                'username' => 'rizki',
                'password' => Hash::make('rizki.123'),
                'role' => 'admin',
                'phone' => '0',
                'email' => 'IT1@pintex.co.id',
                'entitas_all' => '1',
                'entitas_pintex' => '1',
                'entitas_tfi' => '1',
                'p_master' => '1',
                'p_pengadaan' => '1',
                'c_permintaan' => '1',
                'c_persetujuan' => '1',
                'c_email' => '1',
                'c_pembelian' => '1',
                'c_status' => '1',
                'p_gudang' => '1',
                'c_stock' => '1',
                'c_penerimaan' => '1',
                'c_pengiriman' => '1',
                'c_sample' => '1',
                'c_transit' => '1',
                'c_mutasi' => '1',
                'p_teknik' => '1',
                'c_servis' => '1',
                'c_retur' => '1',
                'c_pengambilan' => '1',
                'p_laporan' => '1',
                'c_lap_pemakaian' => '1',
                'c_lap_pembelian' => '1',
                'c_lap_stock' => '1',
                'p_pengaturan' => '1',
                'c_pengguna' => '1',
            ],
            [
                'name' => 'Puji Nurrenti',
                'username' => 'puji',
                'password' => Hash::make('26081997'),
                'role' => 'purchasing',
                'phone' => '0',
                'email' => 'puji@pintex.co.id',
                'entitas_all' => '1',
                'entitas_pintex' => '1',
                'entitas_tfi' => '1',
                'p_master' => '1',
                'p_pengadaan' => '1',
                'c_permintaan' => '1',
                'c_persetujuan' => '1',
                'c_email' => '1',
                'c_pembelian' => '1',
                'c_status' => '1',
                'p_gudang' => '1',
                'c_stock' => '1',
                'c_penerimaan' => '1',
                'c_pengiriman' => '1',
                'c_sample' => '1',
                'c_transit' => '1',
                'c_mutasi' => '1',
                'p_teknik' => '1',
                'c_servis' => '1',
                'c_retur' => '1',
                'c_pengambilan' => '1',
                'p_laporan' => '1',
                'c_lap_pemakaian' => '1',
                'c_lap_pembelian' => '1',
                'c_lap_stock' => '1',
                'p_pengaturan' => '0',
                'c_pengguna' => '0',
            ],

            [
                'name' => 'Fahmi Fahrurrozi',
                'username' => 'fahmi',
                'password' => Hash::make('07081998'),
                'role' => 'whs',
                'phone' => '0',
                'email' => '0',
                'entitas_all' => '0',
                'entitas_pintex' => '1',
                'entitas_tfi' => '1',
                'p_master' => '1',
                'p_pengadaan' => '1',
                'c_permintaan' => '1',
                'c_persetujuan' => '0',
                'c_email' => '0',
                'c_pembelian' => '0',
                'c_status' => '1',
                'p_gudang' => '1',
                'c_stock' => '1',
                'c_penerimaan' => '1',
                'c_pengiriman' => '1',
                'c_sample' => '1',
                'c_transit' => '1',
                'c_mutasi' => '0',
                'p_teknik' => '1',
                'c_servis' => '1',
                'c_retur' => '1',
                'c_pengambilan' => '1',
                'p_laporan' => '0',
                'c_lap_pemakaian' => '0',
                'c_lap_pembelian' => '0',
                'c_lap_stock' => '0',
                'p_pengaturan' => '0',
                'c_pengguna' => '0',
            ],

            [
                'name' => 'Rizky Anurullah R',
                'username' => 'rizki',
                'password' => Hash::make('21091995'),
                'role' => 'whs',
                'phone' => '0',
                'email' => '0',
                'entitas_all' => '0',
                'entitas_pintex' => '1',
                'entitas_tfi' => '0',
                'p_master' => '1',
                'p_pengadaan' => '1',
                'c_permintaan' => '1',
                'c_persetujuan' => '0',
                'c_email' => '0',
                'c_pembelian' => '0',
                'c_status' => '1',
                'p_gudang' => '1',
                'c_stock' => '1',
                'c_penerimaan' => '1',
                'c_pengiriman' => '0',
                'c_sample' => '1',
                'c_transit' => '1',
                'c_mutasi' => '0',
                'p_teknik' => '1',
                'c_servis' => '1',
                'c_retur' => '1',
                'c_pengambilan' => '1',
                'p_laporan' => '0',
                'c_lap_pemakaian' => '0',
                'c_lap_pembelian' => '0',
                'c_lap_stock' => '0',
                'p_pengaturan' => '0',
                'c_pengguna' => '0',
            ],

            [
                'name' => 'Sukmitiyanti',
                'username' => 'yanti',
                'password' => Hash::make('eproc2024'),
                'role' => 'whs',
                'phone' => '0',
                'email' => '0',
                'entitas_all' => '0',
                'entitas_pintex' => '1',
                'entitas_tfi' => '0',
                'p_master' => '1',
                'p_pengadaan' => '1',
                'c_permintaan' => '1',
                'c_persetujuan' => '0',
                'c_email' => '0',
                'c_pembelian' => '0',
                'c_status' => '1',
                'p_gudang' => '1',
                'c_stock' => '1',
                'c_penerimaan' => '1',
                'c_pengiriman' => '0',
                'c_sample' => '1',
                'c_transit' => '1',
                'c_mutasi' => '0',
                'p_teknik' => '1',
                'c_servis' => '1',
                'c_retur' => '1',
                'c_pengambilan' => '1',
                'p_laporan' => '0',
                'c_lap_pemakaian' => '0',
                'c_lap_pembelian' => '0',
                'c_lap_stock' => '0',
                'p_pengaturan' => '0',
                'c_pengguna' => '0',
            ],

            [
                'name' => 'Admin TFI',
                'username' => 'tfi',
                'password' => Hash::make('eproc2024tfi'),
                'role' => 'whs',
                'phone' => '0',
                'email' => '0',
                'entitas_all' => '0',
                'entitas_pintex' => '0',
                'entitas_tfi' => '1',
                'p_master' => '0',
                'p_pengadaan' => '1',
                'c_permintaan' => '1',
                'c_persetujuan' => '0',
                'c_email' => '0',
                'c_pembelian' => '0',
                'c_status' => '1',
                'p_gudang' => '0',
                'c_stock' => '0',
                'c_penerimaan' => '0',
                'c_pengiriman' => '0',
                'c_sample' => '0',
                'c_transit' => '0',
                'c_mutasi' => '0',
                'p_teknik' => '0',
                'c_servis' => '0',
                'c_retur' => '0',
                'c_pengambilan' => '0',
                'p_laporan' => '0',
                'c_lap_pemakaian' => '0',
                'c_lap_pembelian' => '0',
                'c_lap_stock' => '0',
                'p_pengaturan' => '0',
                'c_pengguna' => '0',
            ],

            [
                'name' => 'Alvin Tanuwijaya',
                'username' => 'alvin',
                'password' => Hash::make('Alvinptx1269'),
                'role' => 'own',
                'phone' => '0',
                'email' => 'Alvin@pintex.co.id',
                'entitas_all' => '0',
                'entitas_pintex' => '1',
                'entitas_tfi' => '1',
                'p_master' => '1',
                'p_pengadaan' => '1',
                'c_permintaan' => '1',
                'c_persetujuan' => '1',
                'c_email' => '1',
                'c_pembelian' => '1',
                'c_status' => '1',
                'p_gudang' => '1',
                'c_stock' => '1',
                'c_penerimaan' => '1',
                'c_pengiriman' => '1',
                'c_sample' => '1',
                'c_transit' => '1',
                'c_mutasi' => '1',
                'p_teknik' => '1',
                'c_servis' => '1',
                'c_retur' => '1',
                'c_pengambilan' => '1',
                'p_laporan' => '1',
                'c_lap_pemakaian' => '1',
                'c_lap_pembelian' => '1',
                'c_lap_stock' => '1',
                'p_pengaturan' => '0',
                'c_pengguna' => '0',
            ],

            [
                'name' => 'Brian Setiadinata',
                'username' => 'brian',
                'password' => Hash::make('eproc1269'),
                'role' => 'own',
                'phone' => '0',
                'email' => 'Brian@pintex.co.id',
                'entitas_all' => '0',
                'entitas_pintex' => '1',
                'entitas_tfi' => '1',
                'p_master' => '1',
                'p_pengadaan' => '1',
                'c_permintaan' => '1',
                'c_persetujuan' => '1',
                'c_email' => '1',
                'c_pembelian' => '1',
                'c_status' => '1',
                'p_gudang' => '1',
                'c_stock' => '1',
                'c_penerimaan' => '1',
                'c_pengiriman' => '1',
                'c_sample' => '1',
                'c_transit' => '1',
                'c_mutasi' => '1',
                'p_teknik' => '1',
                'c_servis' => '1',
                'c_retur' => '1',
                'c_pengambilan' => '1',
                'p_laporan' => '1',
                'c_lap_pemakaian' => '1',
                'c_lap_pembelian' => '1',
                'c_lap_stock' => '1',
                'p_pengaturan' => '0',
                'c_pengguna' => '0',
            ],

            [
                'name' => 'Felix Jesse Tan',
                'username' => 'felixjesse',
                'password' => Hash::make('jesse1300'),
                'role' => 'own',
                'phone' => '0',
                'email' => 'Felix@pintex.co.id',
                'entitas_all' => '0',
                'entitas_pintex' => '1',
                'entitas_tfi' => '1',
                'p_master' => '1',
                'p_pengadaan' => '1',
                'c_permintaan' => '1',
                'c_persetujuan' => '1',
                'c_email' => '1',
                'c_pembelian' => '1',
                'c_status' => '1',
                'p_gudang' => '1',
                'c_stock' => '1',
                'c_penerimaan' => '1',
                'c_pengiriman' => '1',
                'c_sample' => '1',
                'c_transit' => '1',
                'c_mutasi' => '1',
                'p_teknik' => '1',
                'c_servis' => '1',
                'c_retur' => '1',
                'c_pengambilan' => '1',
                'p_laporan' => '1',
                'c_lap_pemakaian' => '1',
                'c_lap_pembelian' => '1',
                'c_lap_stock' => '1',
                'p_pengaturan' => '0',
                'c_pengguna' => '0',
            ],

            [
                'name' => 'Akun HRD',
                'username' => 'hrd',
                'password' => Hash::make('eprochrd2024'),
                'role' => 'whs',
                'phone' => '0',
                'email' => 'Pintex_hrd@pintex.co.id',
                'entitas_all' => '0',
                'entitas_pintex' => '1',
                'entitas_tfi' => '0',
                'p_master' => '0',
                'p_pengadaan' => '1',
                'c_permintaan' => '1',
                'c_persetujuan' => '0',
                'c_email' => '0',
                'c_pembelian' => '0',
                'c_status' => '0',
                'p_gudang' => '0',
                'c_stock' => '0',
                'c_penerimaan' => '0',
                'c_pengiriman' => '0',
                'c_sample' => '0',
                'c_transit' => '0',
                'c_mutasi' => '0',
                'p_teknik' => '0',
                'c_servis' => '0',
                'c_retur' => '0',
                'c_pengambilan' => '0',
                'p_laporan' => '0',
                'c_lap_pemakaian' => '0',
                'c_lap_pembelian' => '0',
                'c_lap_stock' => '0',
                'p_pengaturan' => '0',
                'c_pengguna' => '0',
            ],
        ];

        foreach ($user as $key => $value) {
            User::create($value);
        }
    }
}
